-- Todo Assemble
	-- Todo Preprocess String (remove comments)
	-- Todo Tokenize everything
		-- Todo Identifiers
		-- Todo Strings
		-- Todo Numbers
		-- Todo Keywords
		-- Todo Symbols
	-- Todo Parse Tokens
		-- Todo this in multiple stages
			-- Todo (1st) separate instructions, expression, labels, macros, protos
			-- Todo (2nd) handle labels first
			-- Todo (3rd) handle other identifiers
			-- Todo (4th) handle expressions
			-- Todo (5th) do everything else
	-- Todo create custom object format
	-- Todo Create (de)linker for ^

